app:
    auth:
        tokenExpirationMsec: 864000000
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
directory:
    client:
        request:
            file: /image
hostName: http://bienhoa.ga:8080
jwt:
    secret: javanuise
momo:
    accessKey: L8gRL8zpckISGhdl
    baseUrl: https://test-payment.momo.vn
    environment: dev
    partnerCode: MOMO9AJP20211018
    secretKey: SAkWpckiBbJYFXwhMIyFH9ltgrZmMZIC
pathurl: /var/www/live/
server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: P@ssword*123
        url: jdbc:mysql://bienhoa.ga:3306/king_food
        username: tuan
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    security:
        oauth2:
            client:
                provider:
                    facebook:
                        authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
                        tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
                        userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
                registration:
                    facebook:
                        clientId: 907369150136937
                        clientSecret: b880c9aa1d560a4b5c76c61a26e4d9c5
                        redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
                        scope:
                            - email
                            - public_profile
                    github:
                        clientId: d3e47fc2ddd966fa4352
                        clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
                        redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
                        scope: '[user:email, read:user]'
                    google:
                        clientId: 176739962220-or8oc1vi8f6jrvgc6b3b9ta86159q0fd.apps.googleusercontent.com
                        clientSecret: jFzyLLBZnxbiRqpHToQ5w2_Y
                        redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
                        scope:
                            - email
                            - profile

